format = "$directory($git_branch$git_commit$git_state$git_status)($cmd_duration) $fill ($custom$shlvl)$time\n$jobs$character\n"
[aws]
symbol = "  "

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"
vimcmd_replace_one_symbol = "[<](bold purple)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_symbol = "[<](bold yellow)"
vimcmd_visual_symbol = "[<](bold cyan)"

[cmd_duration]
format = "took [$duration]($style) "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[$path]($style)( [$read_only]($read_only_style)) "
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
disabled = false
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[@$hostname]($style) "
ssh_only = false
style = "bold green"

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
disabled = false
format = "[$shlvl]($style) "
repeat = true
style = "bold cyan"
symbol = ""
threshold = 2

[swift]
symbol = "󰛥 "

[terraform]
symbol = "󱁢"

[time]
disabled = false
format = "\\[[$time]($style)\\] "

[username]
format = "[$user]($style)"
show_always = true
